[package]
name = "linux_virtual_joystick"
version = "0.1.0"
authors = ["Abe Zukor <abezukor@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uinput = "0.1.3"
gtk = "0.9.2"
